# https://nodejs.org/en/docs/es6/
sudo: false

language: node_js

branches:
  only:
    - master
    - /^greenkeeper-/

cache:
  directories:
    - node_modules

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "stable"
      env: JOB_PART=test
    - os: linux
      node_js: "7"
      env: JOB_PART=test
    - os: linux
      node_js: "6"
      env: JOB_PART=test

before_install:
  - npm i -g npm@latest
  - nvm --version
  - node --version

before_script:
  - npm prune
  - npm install yarn -g
  - yarn install

script:
  - npm run $JOB_PART:travis

after_sucess:
  - npm run report-coverage
