# https://nodejs.org/en/docs/es6/
sudo: false

language: node_js

node_js:
  - stable

branches:
  only:
    - /^greenkeeper-/
    - master

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: JOB_PART=test
    - os: linux
      node_js: "6"
      env: JOB_PART=test

before_script:
  - npm install yarn -g
  - yarn install

before_install:
  - nvm --version
  - node --version

script:
  - npm run $JOB_PART:travis
