# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
    - /^greenkeeper-/

init:
  - git config --global core.autocrlf input

clone_depth: 50

environment:
  matrix:
    - nodejs_version: stable
      job_part: test
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm prune
  - npm i -g yarn
  - yarn i -g npm@latest
  - yarn install

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - yarn --version
  - cmd: yarn run %job_part%:appveyor

after_test:
  - yarn run report-coverage
