comment: off

codecov:
  branch: master

coverage:
  precision: 2
  range: "75...100"
  round: down

  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
    changes:
      default:
        branches: null
